// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_secLBL;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_dateLBL;
extern lv_obj_t * ui_dayLBL;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_batVoltage;
extern lv_obj_t * ui_batPercent;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Bar1;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label19;
// SCREEN: ui_setMenu
void ui_setMenu_screen_init(void);
extern lv_obj_t * ui_setMenu;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_setTime
void ui_setTime_screen_init(void);
extern lv_obj_t * ui_setTime;
void ui_event_hrUp(lv_event_t * e);
extern lv_obj_t * ui_hrUp;
extern lv_obj_t * ui_Label20;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label14;
void ui_event_minUp(lv_event_t * e);
extern lv_obj_t * ui_minUp;
extern lv_obj_t * ui_Label21;
void ui_event_hrDown(lv_event_t * e);
extern lv_obj_t * ui_hrDown;
extern lv_obj_t * ui_Label22;
void ui_event_minDown(lv_event_t * e);
extern lv_obj_t * ui_minDown;
extern lv_obj_t * ui_Label23;
void ui_event_saveTime(lv_event_t * e);
extern lv_obj_t * ui_saveTime;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_setHrLBL;
extern lv_obj_t * ui_setMinLBL;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel24;
// SCREEN: ui_setDate
void ui_setDate_screen_init(void);
extern lv_obj_t * ui_setDate;
void ui_event_monthUP(lv_event_t * e);
extern lv_obj_t * ui_monthUP;
extern lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label25;
void ui_event_dayUp(lv_event_t * e);
extern lv_obj_t * ui_dayUp;
extern lv_obj_t * ui_Label26;
void ui_event_monthDowm(lv_event_t * e);
extern lv_obj_t * ui_monthDowm;
extern lv_obj_t * ui_Label27;
void ui_event_dayDown(lv_event_t * e);
extern lv_obj_t * ui_dayDown;
extern lv_obj_t * ui_Label28;
void ui_event_saveDate(lv_event_t * e);
extern lv_obj_t * ui_saveDate;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_setMonthLBL;
extern lv_obj_t * ui_setDayLBL;
void ui_event_yearUp(lv_event_t * e);
extern lv_obj_t * ui_yearUp;
extern lv_obj_t * ui_Label30;
void ui_event_yearDown(lv_event_t * e);
extern lv_obj_t * ui_yearDown;
extern lv_obj_t * ui_Label31;
void ui_event_dowUp(lv_event_t * e);
extern lv_obj_t * ui_dowUp;
extern lv_obj_t * ui_Label32;
void ui_event_dowDown(lv_event_t * e);
extern lv_obj_t * ui_dowDown;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_setYearLBL;
extern lv_obj_t * ui_setDowLBL;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png
LV_IMG_DECLARE(ui_img_set_png);    // assets\set.png
LV_IMG_DECLARE(ui_img_bright_png);    // assets\bright.png

LV_FONT_DECLARE(ui_font_date);
LV_FONT_DECLARE(ui_font_day);
LV_FONT_DECLARE(ui_font_digits);
LV_FONT_DECLARE(ui_font_secs);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
