// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


void ui_setEmotion_screen_init(void)
{
    /* ================= SCREEN ================= */
    ui_setEmotion = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setEmotion, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_setEmotion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setEmotion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ================= START / STOP BUTTON ================= */
    ui_Button7 = lv_btn_create(ui_setEmotion);
    lv_obj_set_size(ui_Button7, 100, 50);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_Button7, -8);
    lv_obj_set_y(ui_Button7, -162);
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);

    /* default = STOPPED (RED) */
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x3B9750), LV_PART_MAIN); // GREEN
  


    ui_Label37 = lv_label_create(ui_Button7);
    lv_label_set_text(ui_Label37, "START");
    lv_obj_center(ui_Label37);

    /* ================= HOME BUTTON ================= */
    ui_Button8 = lv_btn_create(ui_setEmotion);
    lv_obj_set_size(ui_Button8, 100, 50);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_Button8, -11);
    lv_obj_set_y(ui_Button8, 151);
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label38 = lv_label_create(ui_Button8);
    lv_label_set_text(ui_Label38, "HOME");
    lv_obj_center(ui_Label38);

    /* ================= STATUS LABEL ================= */
    ui_Label39 = lv_label_create(ui_setEmotion);
    lv_label_set_text(ui_Label39, "IDLE");
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_Label39, -13);
    lv_obj_set_y(ui_Label39, -66);
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_28, LV_PART_MAIN);

    /* ================= EMOJI PANEL ================= */
    ui_Panel26 = lv_obj_create(ui_setEmotion);
    lv_obj_set_size(ui_Panel26, 100, 76);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_Panel26, -7);
    lv_obj_set_y(ui_Panel26, 12);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Panel26, 12, LV_PART_MAIN);

    /* ================= EMOJI LABEL (CENTERED) ================= */
    ui_emojiLabel = lv_label_create(ui_Panel26);
    lv_label_set_text(ui_emojiLabel, "");
    lv_obj_center(ui_emojiLabel);
    lv_obj_set_style_text_font(ui_emojiLabel, &lv_font_montserrat_28, LV_PART_MAIN);

    /* ================= EVENTS ================= */
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_CLICKED, NULL);
}


